version: "3.9"

services:
  app:
    container_name: stonks_bks
    build:
      context: ./..
      dockerfile: deployments/Dockerfile
    ports:
      - "12342:12342"
    env_file:
      - ../configs/config.env
    networks:
      - network
    restart: always
#  O9GVT5VWQWKE2Z5Q
networks:
  network:
    driver: bridge